default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 1024
  mem_per_cpu: 3072
  partition: core

bwa_mem:
  mem_mb: 61440
  mem_per_cpu: 6144
  threads: 10
  time: "8:00:00"

fastp_pe:
  threads: 5
  mem_mb: 30720
  mem_per_cpu: 6144
